feat: command showcase
Olyno/supabase-community-bot pull request #9
Opened 2023-04-09 22:41 UTC by Olyno

## What kind of change does this PR introduce?

This pull request introduces the showcase command.

## What is the current behavior?

The #showcase channel on the discord can be improved, and here is one of the improvements possible.

## What is the new behavior?

The showcase command lets users share their project related to Supabase directly on the Discord.

## Additional context

![See https://cdn.discordapp.com/attachments/843998099033817089/1094748620714168510/Record_select-area_20230410001920.gif](https://cdn.discordapp.com/attachments/843998099033817089/1094748620714168510/Record_select-area_20230410001920.gif)

2023-06-14 17:28 UTC, anand2312 requested changes
Looks pretty good!
Another idea - we could use Discord's [modals](https://discordjs.guide/interactions/modals.html) here, the UI would look neater I think. But I'm not sure if validation of the fields is as easy as it is with the slash command. Thoughts?

2023-06-14 17:28 UTC, anand2312 commented on src/commands/showcase.ts
> +        option
we could use `.setMaxLength` here (and in some of the other fields - maybe project name?) to limit the length of the user input ([doc](https://discordjs.guide/slash-commands/advanced-creation.html#further-validation))

2023-06-14 17:28 UTC, anand2312 commented on src/commands/showcase.ts
> +export const data = new SlashCommandBuilder()
Suggestion: set a cooldown on the command

2023-06-14 17:28 UTC, anand2312 commented on src/commands/showcase.ts
> +export const data = new SlashCommandBuilder()
feel free to just dismiss this btw if cooldownds are not necessary. was just a thought 😄

2023-06-23 17:51 UTC, Olyno commented
Thanks for your patience. I've just pushed the suggestions you gave me. What do you think? @anand2312

2023-06-24 13:46 UTC, anand2312 approved these changes
LGTM!

2023-06-24 13:48 UTC, anand2312 approved these changes
~~Whoops I clicked comment by accident last time 😅 LGTM again!~~ Huh nvm I clicked right. Dunno why it still says review required @Olyno

2023-06-25 16:43 UTC, silentworks approved these changes

2023-06-25 16:44 UTC, merged